services:
  proxy:
    build: 
      context: .
      dockerfile: Dockerfile.proxy
    ports:
      - "8080:80"
      - "8443:443"
      - "5355:53/udp"
      - "1080:1080"
      - "9090:9090"
    volumes:
      - proxy_config:/etc/space-proxy
      - proxy_certs:/app/certs
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
    networks:
      - space-net

  # Optional services that can be commented out if they cause issues
  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9092:9090" # Changed to avoid conflict with port 9091
    volumes:
      - prometheus_data:/prometheus
    networks:
      - space-net
    user: "root"
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.console.libraries=/usr/share/prometheus/console_libraries"
      - "--web.console.templates=/usr/share/prometheus/consoles"

networks:
  space-net:
    driver: bridge

volumes:
  prometheus_data:
  proxy_config:
  proxy_certs: